spring:
  application:
    name: ms-users

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
dh:
  keycloak:
    realm: Examen-BE2
    serverUrl: http://localhost:8080/
    clientGrantType: client_credentials
    clientId: keycloak-client-user
    clientSecret: MVuVQouKtoeCOt3qxILaI1NtqEF2wKEG
server:
  port: 8081
