# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-bills
          uri: lb://ms-bills
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v2/**
          filters:
            - StripPrefix=2
# Configuraciones de seguridad
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/Examen-BE2
        registration:
          api-gateway-service:
            provider: keycloak-provider
            client-id: CL-apiGateway
            client-secret: giTQicfeVrDgKyWFszMDIrCwvZTUeJyN
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
